-- DDL script for table abon for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:19 2022
-- Create table statement

SET DEFINE OFF


BEGIN
   EXECUTE IMMEDIATE ' DROP TABLE abon CASCADE CONSTRAINTS';
   EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE abon
(
   id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY(START WITH 4 INCREMENT BY 1)   NOT NULL,
   descr NCLOB,
   price NUMBER(10,0),
   halId NUMBER(10,0)
);


-- Primary key

ALTER TABLE abon ADD  CONSTRAINT PK__abon__3213E83F0CC72ABC
PRIMARY KEY(id);


ALTER TABLE abon ADD  CONSTRAINT FK_Anon_To_Hal
FOREIGN KEY(halId)
REFERENCES hal(id)   
-- ON DELETE NO ACTION was removed since such behaviour is default while NO ACTION keyword(s) not supported
  ;

EXIT;

