@echo off
if %SQLWAYS_CMD_ECHO%==on (@echo on)
echo.
echo Importing table abon to Oracle
setlocal enabledelayedexpansion
rem Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
rem Timestamp: Tue May 17 21:56:19 2022

rem --------------------------------------------------------------
rem How to use this command file:

rem To create table, constraints, import data and create indexes run:
rem 	abon.bat all

rem To create table and its constraints run:
rem 	abon.bat table

rem To import data into the table run:
rem 	abon.bat import

rem To create indexes for the table run:
rem 	abon.bat idx

rem To execute all DDL statements for the table run:
rem 	abon.bat ddl

rem --------------------------------------------------------------
rem Define a task to perform


@echo off

for %%x in (%*) do (
  if "%%~x"=="table" call:create_table
  if "%%~x"=="import" call:import_data
  if "%%~x"=="idx" call:create_idx
  if "%%~x"=="all" (
    call:create_table
    call:import_data
    call:create_idx
  )
)
@echo %SQLWAYS_CMD_ECHO%
goto end

rem --------------------------------------------------------------
:create_table
echo Creating table and its constraints using the Oracle SQL*Plus utility

D:\\app\\ora_install_user\\product\\12.1.0\\dbhome_1\\BIN\sqlplus system/Apahar33 @abon_ddl.sql
goto:eof

rem --------------------------------------------------------------
:import_data
echo Importing data using the Oracle SQL*Loader utility

D:\\app\\ora_install_user\\product\\12.1.0\\dbhome_1\\BIN\sqlldr userid=system/Apahar33 control=abon.ctl log=abon.log rows=1000 readsize=71000 bindsize=71000



echo Altering identity column to implement generate always as identity

D:\\app\\ora_install_user\\product\\12.1.0\\dbhome_1\\BIN\sqlplus system/Apahar33 @abon_id.sql
goto:eof

rem --------------------------------------------------------------
:create_idx
echo Creating indexes using the Oracle SQL*Plus utility

D:\\app\\ora_install_user\\product\\12.1.0\\dbhome_1\\BIN\sqlplus system/Apahar33 @abon_idx.sql
goto:eof



rem --------------------------------------------------------------
:end


rem End script
