-- Stored procedure definition script dbo.AddCoachUsingHierarchy for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----

create procedure AddCoachUsingHierarchy (@fio nvarchar(100),
											@payment int,
											@parentId hierarchyId)
as
begin
begin try
declare @LCV hierarchyid
	begin transaction
		select @LCV=max(parentId)
		from coach where
		parentId.GetAncestor(1)=@parentId;
	insert into coach(FIO, payment, parentId)
	values (@FIO, @payment, @parentId.GetDescendant(@LCV,NULL));
	commit;
end try
BEGIN CATCH
    print ERROR_NUMBER() + ERROR_MESSAGE();
END CATCH
end;
/

SHOW ERRORS;

EXIT;

