-- Stored procedure definition script dbo.CalculateShortestPath2 for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----


create procedure CalculateShortestPath2(@p1 nvarchar(100), @p2 nvarchar(100))
as
begin
	declare @g1 geometry = GEOMETRY::STGeomFromText(@p1,0);
	declare @g2 geometry = GEOMETRY::STGeomFromText(@p2,0);
	declare @distance float = @g1.STDistance(@g2);
	declare @line geometry;
	select @distance as 'Distance';
	select @line = @g1.ShortestLineTo(@g2);
	
end
/

SHOW ERRORS;

EXIT;

