-- Stored procedure definition script dbo.change_client for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----

create   procedure change_client
    @id int,
    @Secondname nvarchar(max),
    @Firstname nvarchar(max),
    @Phone nvarchar(max),
    @CoachId int
as
    begin
        update client set SecondName = @Secondname, FirstName = @Firstname, Phone = @Phone, coachId = @CoachId
            where id = @id;
        select 0;
    end
/

SHOW ERRORS;

EXIT;

