-- DDL script for table client for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:23 2022
-- Create table statement

SET DEFINE OFF


BEGIN
   EXECUTE IMMEDIATE ' DROP TABLE client CASCADE CONSTRAINTS';
   EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE client
(
   id NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY(START WITH 23 INCREMENT BY 1)   NOT NULL,
   SecondName NVARCHAR2(30),
   FirstName NVARCHAR2(30),
   Phone NVARCHAR2(15),
   coachId NUMBER(10,0)
);


-- Primary key

ALTER TABLE client ADD  CONSTRAINT PK__client__3213E83F40720222
PRIMARY KEY(id);


ALTER TABLE client ADD  CONSTRAINT FK_Client_To_Coach
FOREIGN KEY(coachId)
REFERENCES coach(id)   
-- ON DELETE NO ACTION was removed since such behaviour is default while NO ACTION keyword(s) not supported
  ;

EXIT;

