-- DDL script for indexes for table client for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:23 2022
SET DEFINE OFF

CREATE
INDEX indexClient
ON
client
(id ASC);

EXIT;

