-- Stored procedure definition script dbo.EnlargeLocation for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----

	create   procedure EnlargeLocation @id int, @pnt geometry
	as
	begin
	declare @location geometry;
	select @location = point
	from SportPlaces
	where Id = @id;
	update SportPlaces set point = CAST((@location.STBuffer(@pnt.STDistance(@location))) AS nvarchar)
	where ID = @id;
	end;
/

SHOW ERRORS;

EXIT;

