-- DDL script for indexes for table gadm40_blr_2 for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:25 2022
SET DEFINE OFF

CREATE
INDEX index_shape
ON
gadm40_blr_2
(ogr_geometry ASC);


--Ispirer Comment: such column list already indexed
----CREATE
----         INDEX ogr_dbo_gadm40_blr_2_ogr_geometry_sidx
----        ON
----        dbo.gadm40_blr_2
----(ogr_geometry ASC);

EXIT;

