-- DDL script for table gadm40_blr_2 for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:25 2022
-- Create table statement

SET DEFINE OFF


BEGIN
   EXECUTE IMMEDIATE ' DROP TABLE gadm40_blr_2 CASCADE CONSTRAINTS';
   EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE gadm40_blr_2
(
   ogr_fid NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY(START WITH 119 INCREMENT BY 1)   NOT NULL,
   ogr_geometry CLOB,
   id_0 NVARCHAR2(32),
   country NVARCHAR2(32),
   name_1 NVARCHAR2(32),
   nl_name_1 NVARCHAR2(32),
   id_2 NVARCHAR2(32),
   name_2 NVARCHAR2(32),
   varname_2 NVARCHAR2(32),
   nl_name_2 NVARCHAR2(38),
   type_2 NVARCHAR2(32),
   engtype_2 NVARCHAR2(32),
   cc_2 NVARCHAR2(32),
   hasc_2 NVARCHAR2(32) 
);


-- Primary key

ALTER TABLE gadm40_blr_2 ADD  CONSTRAINT PK_gadm40_blr_2
PRIMARY KEY(ogr_fid);

EXIT;

