-- DDL script for table geometry_columns for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:27 2022
-- Create table statement

SET DEFINE OFF


BEGIN
   EXECUTE IMMEDIATE ' DROP TABLE geometry_columns CASCADE CONSTRAINTS';
   EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE geometry_columns
(
   f_table_catalog VARCHAR2(128)   NOT NULL,
   f_table_schema VARCHAR2(128)   NOT NULL,
   f_table_name VARCHAR2(256)   NOT NULL,
   f_geometry_column VARCHAR2(256)   NOT NULL,
   coord_dimension NUMBER(10,0)  NOT NULL,
   srid NUMBER(10,0)  NOT NULL,
   geometry_type VARCHAR2(30)   NOT NULL
);


-- Primary key

ALTER TABLE geometry_columns ADD  CONSTRAINT geometry_columns_pk
PRIMARY KEY(f_table_catalog,f_table_schema,f_table_name,f_geometry_column);

EXIT;

