@echo off
if %SQLWAYS_CMD_ECHO%==on (@echo on)
echo Importing stored procedure dbo.getAllClients to Oracle
rem Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
rem Timestamp: Tue May 17 21:56:32 2022

rem --------------------------------------------------------------

D:\\app\\ora_install_user\\product\\12.1.0\\dbhome_1\\BIN\sqlplus system/Apahar33 @getallclients.sql

rem --------------------------------------------------------------


rem End script
