-- Stored procedure definition script dbo.GetPlaceMap for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----


create procedure GetPlaceMap
as
begin
	set nocount on;
	create table #Points(point geometry);
	declare points_cursor cursor for
	select point from SportPlaces;
	declare @g geometry;
	open points_cursor
	fetch next from points_cursor
	into @g;
	while @@FETCH_STATUS = 0
	begin
		insert into #Points values (@g);
		fetch next from points_cursor
		into @g;
	end
	select ogr_geometry.STAsText() from gadm40_blr_2
	union all
	select point.STBuffer(0.07).STAsText() from #Points;
	
	close points_cursor
	deallocate points_cursor
	drop table #Points;
end;
/

SHOW ERRORS;

EXIT;

