-- Stored procedure definition script dbo.insertRecord for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----

create   procedure insertRecord
as
    begin try
        insert into record values (99,3,'2022-02-02','2022-04-02',1)
    end try
    begin catch
    end catch
/

SHOW ERRORS;

EXIT;

