-- Trigger definition script insertClientMessage for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

create   or replace trigger insertClientMessage
after insert
on client
   DECLARE
   ERROR_MESSAGE varchar2(4000);
BEGIN
   open v_refcur for select('Клиент был успешно добавлен') from dual;
   dbms_sql.return_result(v_refcur);
   EXCEPTION WHEN OTHERS THEN
      /*NOT SUPPORTED rollback;*/
ERROR_MESSAGE := SQLERRM;
      open v_refcur2 for select ERROR_MESSAGE as ErrorMessage from dual;
      dbms_sql.return_result(v_refcur2);
END;

/

SHOW ERRORS;

EXIT;

