-- Function definition script dbo.isAllowed for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----

create   function isAllowed(@currentDate as date)
returns @records table(
    clientId int,
    abonId int,
    startAbon date,
    endAbon date,
    isPaid bit)
    as
    begin
        insert into @records
        select * from record where @currentDate between startAbon and endAbon
        return
    end
/

SHOW ERRORS;

EXIT;

