-- Stored procedure definition script dbo.moveHid for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:32 2022
SET DEFINE OFF

--Warning: object conversion was canceled because of license limitations. The target script equals to the source script.
----

Create procedure moveHid
	@OldParent hierarchyid, 
	@NewParent hierarchyid  
as
begin
DECLARE children_cursor CURSOR FOR  
	SELECT parentId FROM coach  
	WHERE parentId.GetAncestor(1) = @OldParent;  
DECLARE @ChildId hierarchyid;  
OPEN children_cursor  
FETCH NEXT FROM children_cursor INTO @ChildId;  
WHILE @@FETCH_STATUS = 0  
BEGIN  
START:  
    DECLARE @NewId hierarchyid;  
    SELECT @NewId = @NewParent.GetDescendant(MAX(parentId), NULL)  
    FROM coach WHERE parentId.GetAncestor(1) = @NewParent;  

    UPDATE coach 
    SET parentId = parentId.GetReparentedValue(@ChildId, @NewId)  
    WHERE parentId.IsDescendantOf(@ChildId) = 1;  
    IF @@error <> 0 GOTO START -- On error, retry  
        FETCH NEXT FROM children_cursor INTO @ChildId;  
END  
CLOSE children_cursor;  
DEALLOCATE children_cursor;  
end;
/

SHOW ERRORS;

EXIT;

