-- DDL script for table record for Oracle
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:30 2022
-- Create table statement

SET DEFINE OFF


BEGIN
   EXECUTE IMMEDIATE ' DROP TABLE record CASCADE CONSTRAINTS';
   EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE record
(
   clientId NUMBER(10,0),
   abonId NUMBER(10,0),
   startAbon DATE,
   endAbon DATE,
   isPaid NUMBER(1,0),
   placeId NUMBER(10,0)
);


ALTER TABLE record ADD  CONSTRAINT FK_Recor_To_Abon
FOREIGN KEY(abonId)
REFERENCES abon(id)   
-- ON DELETE NO ACTION was removed since such behaviour is default while NO ACTION keyword(s) not supported
  ;


ALTER TABLE record ADD  CONSTRAINT FK_Recor_To_Client
FOREIGN KEY(clientId)
REFERENCES client(id)   
-- ON DELETE NO ACTION was removed since such behaviour is default while NO ACTION keyword(s) not supported
  ;


ALTER TABLE record ADD  CONSTRAINT FK__record__placeId__3429BB53
FOREIGN KEY(placeId)
REFERENCES SportPlaces(id)   
-- ON DELETE NO ACTION was removed since such behaviour is default while NO ACTION keyword(s) not supported
  ;


--Foreign key is commented since it is identical to the previous foreign key
--ALTER TABLE dbo.record ADD  CONSTRAINT FK__record__placeId__6ABAD62E
-- FOREIGN KEY (placeId)
--REFERENCES dbo.SportPlaces (id)   
---- ON DELETE NO ACTION was removed since such behaviour is default while NO ACTION keyword(s) not supported
--

EXIT;

