-- Control file for Oracle SQL Loader
-- Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
-- Timestamp: Tue May 17 21:56:30 2022

OPTIONS(direct=false)
LOAD DATA
INFILE 'record.txt'
INTO TABLE record
INSERT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(clientId,
 abonId,
 startAbon,
 endAbon,
 isPaid,
 placeId)
