rem Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
rem Timestamp: Tue May 17 21:56:32 2022


cd "D:\Soft\Ispirer"
SQLWays.exe  /D=SportPlace /SROW=1 /TARGET=Oracle /TU=system /TP=Apahar33 /IMPORD=Clean /IMPS=Windows /DIR=D:\Study\Practice\DB_6sem\Lab6\Export /STDEL=; /INI=D:\Study\Practice\DB_6sem\Lab6\sqlways_db.ini /PRJF=D:\Study\Practice\DB_6sem\Lab6\sqlways.xml /NSTOP /GCMD=sqlways_all.bat /LOG=sqlways.log /RPT=reports
"D:\Study\Practice\DB_6sem\Lab6\Export\sqlways_all.bat"
rem End script
