@echo off
if "%1"=="echo" (
  @echo on
  set SQLWAYS_CMD_ECHO=on
) else (
  @echo off
  set SQLWAYS_CMD_ECHO=off
)
echo.
echo Importing database objects to Oracle
setlocal enabledelayedexpansion
rem Generated by (c) Ispirer SQLWays 10.22.3 Build 6944 64bit Licensed to BSTU - Timothey - Belarus - Ispirer MnMTK 10 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20220611)
rem Timestamp: Tue May 17 21:56:32 2022

rem --------------------------------------------------------------
rem How to use this command file:

rem To import all database objects and data run:
rem 	sqlways_all.bat all

rem To import tables without data run:
rem 	sqlways_all.bat table

rem To import data into all tables run:
rem 	sqlways_all.bat import

rem To create indexes for all tables run:
rem 	sqlways_all.bat idx

rem To import all database objects without data run:
rem 	sqlways_all.bat ddl

rem To import database objects of specific type run:
rem sqlways_all.bat typename [ typename]*
rem where typename = {view|business_logic_object|trigger|user_defined_type|sequence|synonym}

rem --------------------------------------------------------------
rem --------------------------------------------------------------

@echo off

set table_import_arg=
set import_table=false
set import_view=false
set import_business_logic_object=false
set import_trigger=false
set import_user_defined_type=false
set import_sequence=false
set import_synonym=false
for %%x in (%*) do (
  set is_table_arg=false
  if "%%~x"=="table" set is_table_arg=true
  if "%%~x"=="import" set is_table_arg=true
  if "%%~x"=="ddl" set is_table_arg=true
  if "%%~x"=="idx" set is_table_arg=true
  if "%%~x"=="cns" set is_table_arg=true
  if "!is_table_arg!"=="true" (
    set import_table=true
    set table_import_arg=!table_import_arg! %%~x
  )
  if "%%~x"=="view" set import_view=true
  if "%%~x"=="business_logic_object" set import_business_logic_object=true
  if "%%~x"=="trigger" set import_trigger=true
  if "%%~x"=="user_defined_type" set import_user_defined_type=true
  if "%%~x"=="sequence" set import_sequence=true
  if "%%~x"=="synonym" set import_synonym=true
  if "%%~x"=="all" (
    set table_import_arg=all
    set import_table=true
    set import_view=true
    set import_business_logic_object=true
    set import_trigger=true
    set import_user_defined_type=true
    set import_sequence=true
    set import_synonym=true
  )
)
@echo %SQLWAYS_CMD_ECHO%
rem --------------------------------------------------------------

echo Import initialization
call "swf_object_id.bat"

rem --------------------------------------------------------------

if "%import_table%"=="true" goto import_tables
goto endif_import_tables

:import_tables
echo Importing tables ordered by referential constraints, 9 tables

call  "hal.bat" %table_import_arg%
call  "abon.bat" %table_import_arg%
rem	References: hal
call  "coach.bat" %table_import_arg%
call  "client.bat" %table_import_arg%
rem	References: coach
call  "gadm40_blr_2.bat" %table_import_arg%
call  "geometry_columns.bat" %table_import_arg%
call  "sportplaces.bat" %table_import_arg%
call  "record.bat" %table_import_arg%
rem	References: SportPlaces, abon, client
call  "spatial_ref_sys.bat" %table_import_arg%

:endif_import_tables


if "%import_view%"=="true" goto import_views
goto endif_import_views

:import_views
echo Importing views ordered by dependency, 2 views

call "highpaidcoach.bat"
call "paidclients.bat"

:endif_import_views

rem --------------------------------------------------------------

if "%import_business_logic_object%"=="true" goto import_business_logic_objects
goto endif_import_business_logic_objects

:import_business_logic_objects
echo Importing stored procedures ordered by dependency, 28 stored procedures

call "add_client.bat"
call "add_coach.bat"
call "add_hal.bat"
call "addcoachusinghierarchy.bat"
call "addsportplace.bat"
call "allsportplaces.bat"
call "calculateshortestpath.bat"
call "calculateshortestpath2.bat"
call "change_client.bat"
call "change_coach.bat"
call "change_hal.bat"
call "checkpass.bat"
call "drop_client.bat"
call "drop_coach.bat"
call "drop_hal.bat"
call "enlargelocation.bat"
call "getallclients.bat"
call "getallcoaches.bat"
call "getallhals.bat"
call "getcount.bat"
call "getcoveragemap.bat"
call "getplacemap.bat"
call "getstoragemap.bat"
call "insertclient.bat"
call "insertcoach.bat"
call "insertrecord.bat"
call "movehid.bat"
call "selecthid.bat"

rem --------------------------------------------------------------
echo Importing functions ordered by dependency, 3 functions

call "fn_diagramobjects.bat"
call "isallowed.bat"

rem --------------------------------------------------------------

:endif_import_business_logic_objects

if "%import_trigger%"=="true" goto import_triggers
goto endif_import_triggers

:import_triggers
echo Importing triggers ordered by dependency, 2 triggers

call "insertclientmessage.bat"
call "insertcoachmessage.bat"

:endif_import_triggers

rem --------------------------------------------------------------

rem End script
