set SERVEROUTPUT ON;
create table Report 
(
    id NUMBER GENERATED by default on null as IDENTITY,
    xm XMLTYPE
);

--task2

insert into record values (10,1,TO_DATE('22/3/2011','DD/MM/YY'),TO_DATE('22/3/2017','DD/MM/YY'),0,12);
insert into record values (11,2,TO_DATE('23/2/2013','DD/MM/YY'),TO_DATE('23/4/2016','DD/MM/YY'),0,13);
insert into record values (14,3,TO_DATE('24/1/2012','DD/MM/YY'),TO_DATE('24/5/2018','DD/MM/YY'),0,15);

select * from abon
select * from CLIENT
select * from record
select * from SportPlaces

--task2
create or replace procedure expsessions as
 CTX    dbms_xmlgen.ctxHandle;
 XML    CLOB;
BEGIN
CTX := DBMS_XMLGEN.NEWCONTEXT('select client.FirstName, abon.descr  from record
          inner join client on Client.id = record.clientid
          inner join abon on abon.id = record.abonid where rownum = 1'); 
--DBMS_XMLGEN.SETROWSETTAG(CTX, 'PULPIT'); 
XML := dbms_xmlgen.getXML(CTX);
dbms_output.put_line(XML);
end;

exec expsessions;
set SERVEROUTPUT ON

--task3
create or replace function CreateXML 
return xmltype 
as
  xml xmltype;
  b      NVARCHAR2(600);
begin
   b:= 'select client.FirstName, abon.descr  from record
          inner join client on Client.id = record.clientid
          inner join abon on abon.id = record.abonid'  ;
        
  dbms_output.put_line(b);
        
  select xmlelement("XML",
      xmlelement(evalname('Tab'),
      dbms_xmlgen.getxmltype( b )))
  into xml
  from dual;
  return xml;
end CreateXML;

CREATE OR REPLACE PROCEDURE INSERTXML_PROC(
    id integer,
    x IN XMLTYPE)
IS
BEGIN
  INSERT INTO Report (id, xm) 
  VALUES (id, x);
  COMMIT;
END;

begin 
    INSERTXML_PROC(5, CreateXML);
end;

select * from Report

--task4
create index xml_index on Report(extractvalue(xm,'/XML/text()')); 

--task5
create or replace procedure findProcedure(word  in VARCHAR2, aa out VARCHAR2 ) 
is
begin
      select r.xm.GETSTRINGVAL() xml
      into aa from report r
      where r.xm.EXISTSNODE('/XML')=1;
end findProcedure;
-----------
select * from report;
--------------------
DECLARE 
    word VARCHAR2(4000); 
BEGIN
  findProcedure('delete param', word);
  DBMS_OUTPUT.PUT_LINE( word );
END;


set SERVEROUTPUT ON